config/routes.rb
Blog::Application.routes.draw do |map|
  root :to => "articles#index"
  resources :articles do
  	member do
  	  post :notify_friend
    end
  	resources :comments
  end
    
  resources :users
  resource :session
  match '/login' => "sessions#new", :as => 'login'
  match '/logout' => "sessions#destroy", :as => 'logout'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :presence => true
  validates :body, :presence => true
 
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments
 
  scope :published, where("articles.published_at IS NOT NULL")
  scope :draft, where("articles.published_at IS NULL")
  scope :recent, lambda { published.where("articles.published_at > ?", 1.week.ago.to_date)}
  scope :where_title, lambda { |term| where("articles.title LIKE ?", "%#{term}%") }
 
  def long_title
    "#{title} - #{published_at}"
  end
  
  def published?
    published_at.present?
  end

  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles

  default_scope order('categories.name')
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  
  validates :name, :email, :body, :presence => true
  validate :article_should_be_published

  def article_should_be_published
    errors.add(:article_id, "is not published yet") if article && !article.published?
  end  
end

app/models/comment_observer.rb
class CommentObserver < ActiveRecord::Observer
  def after_create(comment)
   Notifier.comment_added(comment).deliver
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  
  validates :email, :uniqueness => true, 
                    :length => { :within => 5..50 }, 
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  validates :password, :confirmation => true,
                       :length => { :within => 4..20 },
                       :presence => true,
                       :if => :password_required?

  has_one :profile
  has_many :articles, :order => 'published_at DESC, title ASC',
                      :dependent => :nullify
  has_many :replies, :through => :articles, :source => :comments

  before_save :encrypt_new_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end

    def password_required?
      hashed_password.blank? || password.present?
    end

    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected 
    # Returns the currently logged in user or nil if there isn't one
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id]) 
    end

    # Make current_user available in templates as a helper
    helper_method :current_user

    # Filter method to enforce a login requirement
    # Apply as a before_filter on any controller you want to protect
    def authenticate
      logged_in? ? true : access_denied
    end

    # Predicate method to test for a logged in user    
    def logged_in?
      current_user.is_a? User
    end

    # Make logged_in? available in templates as a helper
    helper_method :logged_in?

    def access_denied
      redirect_to login_path, :notice => "Please log in to continue" and return false
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :notify_friend]

  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = current_user.articles.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = current_user.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end

  def notify_friend
  	@article = Article.find(params[:id])
  	Notifier.email_friend(@article, params[:name], params[:email]).deliver
  	redirect_to @article, :notice => "Successfully sent a message to your friend"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_filter :load_article

  def create
    @comment = @article.comments.new(params[:comment])
     
    if @comment.save

     respond_to do |format|
        format.html{redirect_to @article, :notice => 'Thanks for your comment'}
        format.js
     end
    else
      respond_to do |format|
        format.html{redirect_to @article, :alert => 'Unable to add comment'}
        format.js {render 'fail_create.js.erb'}
      end
    end
  end
  
  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
      respond_to do |format|
        format.html{redirect_to @article, :notice => 'Comment deleted'}
        format.js
      end
  end


private
 
 def load_article
  @article = Article.find(params[:article_id])
 end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	
    end

	def create
		if user = User.authenticate(params[:email], params[:password])
			session[:user_id] = user.id
			redirect_to root_path, :notice => "Logged in successfully"
		else
		    flash.now[:alert] = "Invalid email/password combination"
		    render 'new'
        end
    end

    def destroy
    	reset_session
    	redirect_to root_path, :notice => "You seccessfully loged out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :authenticate, :only => [:edit, :update]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to articles_path, :notice => 'User successfully added.'
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to articles_path, :notice => 'Updated user information successfully.'
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def submit_or_cancel(form, name = "Cancel")
		form.submit + " or " + link_to(name, 'javascript:history.go(-1);', :class => 'cancel')
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
  <h3>
    <%= link_to article.title, article %>
    <% if article.owned_by? current_user %>
      <span class='actions'>
        <%= link_to "Edit", edit_article_path(article) %>
        <%= link_to "Delete", article, :confirm => "Are you sure?", :method => :delete %>
      </span>
    <% end %>
  </h3>
  <%= simple_format article.body %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label "Categories" %><br />
    <% for category in Category.all %>
      <%= check_box_tag 'article[category_ids][]', category.id, 
        @article.category_ids.include?(category.id), :id => dom_id(category) %>
      <%= label_tag dom_id(category), category.name, :class => "check_box_label" %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_field :excerpt %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/articles/_notify_friend.html.erb
<%= form_tag(notify_friend_article_path(@article), :id => 'notify_friend_form', :style => 'display:none') do %>
  <div class="field">
    <%= label_tag :name, 'Your name' %><br />
    <%= text_field_tag :name %>
  </div>
  <div class="field">
    <%= label_tag :email, "Your friend's email" %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="actions">
    <%= submit_tag 'Send' %> or
    <%= link_to 'Cancel', '#', :onclick => "$('#notify_friend_form').slideUp()" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<div id="articles">
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>

<%= link_to "Email a Friend", "#", :onclick => "$('#notify_friend_form').slideDown()"%>
<%= render 'notify_friend'%>

<h3>Comments</h3>

<div id="comments">
  <%= render @article.comments %>
</div>
<%= link_to "new comment", new_article_comment_path(@article, :format => :js), :remote => true, :id => 'new_comment_link' %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <h3>
    <%= comment.name %> &lt;<%= comment.email %>&gt; said:
   <% if @article.owned_by? current_user%>
    <span class='actions'>
      <%= link_to 'Delete', [@article, comment], :confirm => 'Are you sure?', :method => :delete, :remote => true %>
    </span>
   <% end%>
  </h3>
  <%= comment.body %>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%=escape_javascript(render(@comment)) %>");
$('#new_comment')[0].reset();

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment)%>").remove();

app/views/comments/fail_create.js.erb
alert("<%= @comment.errors.full_messages.to_sentence%>");

app/views/comments/new.html.erb
<%= form_for([@article, @article.comments.new], :remote => true, :html => {:style => 'display: none;'}
) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Add' %>
  </div>
<% end %>

app/views/comments/new.js.erb
$("<%= escape_javascript render(:file => 'comments/new.html.erb') %>").insertAfter('#comments');
$('#new_comment').slideDown();
$('#new_comment_link').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2.min', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <h1><%= link_to "Blog", root_path %></h1>
    <div id="user_bar">
      <% if logged_in? %>
        <%= link_to "New Article", new_article_path %> |
        <%= link_to "Edit Password", edit_user_path(current_user) %> |
        <%= link_to "Logout", logout_path %>
      <% else %>
        <%= link_to "Login", login_path %>
      <% end %>
    </div>
  </div>
  <div id="main">
    <%= content_tag(:p, notice, :class => 'notice') if notice.present? %>
    <%= content_tag(:p, alert, :class => 'alert') if alert.present? %>
    <%= yield %>
  </div>
  <div id="footer">
    A simple blog built for the book 
<a href="http://beginningrails.com">Beginning Rails 3</a>
  </div>
</body>
</html>

app/views/notifier/comment_added.html.erb
<html>
<body>
  <p>
    Someone added a comment to one of your articles <i><%= @article.title %></i>.
    Go read the comment: <%= link_to @article.title, article_url(@article, :host => 'localhost:3000') %>.
  </p>
</body>
</html>

app/views/notifier/email_friend.html.erb
<html>
<body>
<p>
  One of your friends, <%= @sender_name %>,
  thinks you like an article we have written.
</p>

<p>
  Come check all the information about <strong><%= @article.title %></strong> at
  <%= article_url @article, :host => 'localhost:3000' %>
</p>
</body>
</html>

app/views/notifier/email_friend.text.erb
Your friend <%= @sender_name %> thinks you may like the following article:
<%= @article.title %>: <%= article_url(@article, :host => "localhost:3000") %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>